version: "3.8"

services:
  etf_worker:
    image: howardlch/etf_crawler:1.3
    command: >
      uv run celery -A crawler.worker worker
      --loglevel=info
      --hostname=etf_worker@%h
      --concurrency=1
      -Q twse
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      WORKER_ACCOUNT: worker
      WORKER_PASSWORD: worker
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_ACCOUNT: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    networks:
      - my_swarm_network
      - my_attachable_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.role==manager]  # ETF Worker 跑在 manager VM
      restart_policy:
        condition: any

networks:
  my_swarm_network:
    external: true
  my_attachable_network:
    external: true
    