services:
  crawler_twse:
    image: linsamtw/tibame_crawler:${DOCKER_IMAGE_VERSION}
    hostname: "twse"
    command: uv run --env-file=.env celery -A crawler.worker worker --loglevel=info --hostname=%h -Q twse
    restart: always
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./crawler:/crawler/crawler
      - ./.env:/crawler/.env
    networks:
      - my_network

  crawler_tpex:
    image: linsamtw/tibame_crawler:${DOCKER_IMAGE_VERSION}
    hostname: "tpex"
    command: uv run --env-file=.env celery -A crawler.worker worker --loglevel=info --hostname=%h -Q tpex
    restart: always
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./crawler:/crawler/crawler
      - ./.env:/crawler/.env
    networks:
      - my_network

networks:
  my_network:
    external: true
